export { default as Logo } from './images/logoBanner.png';
export { default as BannerImage } from './images/bannerCouple.png';
export { default as Ultimate1 } from './images/ultimate_plan_1.png';
export { default as Ultimate2 } from './images/ultimate_plan_2.png';
export { default as Ultimate3 } from './images/ultimate_plan_3.png';
export { default as Ultimate4 } from './images/ultimate_plan_4.png';
export { default as Detox1 } from './images/detox1.png';
export { default as Detox2 } from './images/detox2.png';
export { default as WeightManagement1 } from './images/weight_management_1.png';
export { default as WeightManagement2 } from './images/weight_management_2.png';
export { default as WeightManagement3 } from './images/weight_management_3.png';
export { default as Experience1 } from './images/experience_1.png';
export { default as Experience2 } from './images/experience_2.png';
export { default as Experience3 } from './images/experience_3.png';
export { default as Experience4 } from './images/experience_4.png';
export { default as Experience5} from './images/experience_5.png';
export { default as Experience6 } from './images/experience_6.png';
export { default as Experience7 } from './images/experience_7.png';